# Usage: conda env create -f environment.yml
---
channels:
- defaults
- conda-forge
- etetoolkit
dependencies:
- reentry==1.2.2
- python-dateutil==2.8.0
- python-mimeparse==1.6.0
- django==1.7.11
- django-extensions==1.5.0
- tzlocal==1.5.1
- pytz==2018.9
- PyYAML==3.13
- six==1.12.0
- future==0.17.1
- pathlib2==2.3.3
- celery==4.2.1
- billiard==3.3.0.23
- amqp==2.4.1
- anyjson==0.3.3
- plumpy==0.7.12
- portalocker==1.4.0
- psutil==5.5.1
- meld3==1.0.2
- numpy==1.16.2
- SQLAlchemy==1.0.19
- SQLAlchemy-Utils==0.33.0
- alembic==1.0.7
- ujson==1.35
- enum34==1.1.6
- voluptuous==0.11.5
- aldjemy==0.9.1
- passlib==1.7.1
- validate_email==1.3
- click==6.7
- click-plugins==1.0.4
- click-spinner==0.1.8
- tabulate==0.8.3
- ete3==3.1.1
- uritools==2.2.0
- psycopg2==2.7.4
- paramiko==2.4.2
- ecdsa==0.13
- ipython<6.0
name: aiida
