# Usage: conda env create -f environment.yml
---
channels:
- defaults
- conda-forge
- etetoolkit
dependencies:
- reentry==1.2.2
- python-dateutil==2.7.2
- python-mimeparse==1.6.0
- django==1.11.16
- tzlocal==1.5.1
- pytz==2018.4
- PyYAML==3.12
- six==1.11.0
- anyjson==0.3.3
- psutil==5.4.5
- meld3==1.0.2
- mock==2.0.0
- numpy==1.14.3
- SQLAlchemy==1.2.12
- SQLAlchemy-Utils==0.33.0
- alembic==0.9.9
- ujson==1.35
- aldjemy==0.8.0
- passlib==1.7.1
- validate_email==1.3
- click==6.7
- click-completion==0.3.1
- click-plugins==1.0.3
- click-spinner==0.1.7
- tabulate==0.8.2
- ete3==3.1.1
- uritools==2.1.0
- psycopg2==2.7.4
- paramiko==2.4.2
- ecdsa==0.13
- ipython>=4.0,<6.0
- plumpy==0.12.1
- kiwipy[rmq]==0.4.2
- circus==0.14.0
- tornado==4.5.3
- pyblake2==1.1.2; python_version<"3.6"
- chainmap; python_version<"3.5"
- pathlib2; python_version<"3.5"
- singledispatch>=3.4.0.3; python_version<"3.5"
- enum34==1.1.6; python_version<"3.5"
- simplejson==3.16.0
- typing==3.6.6; python_version<"3.5"
name: aiida
